import { type NextPage } from "next";
import Head from "next/head";

import Header from "../components/Header";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Sultan Entertainment</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-full h-[3000px]">
        <Header />
      </main>
    </>
  );
};

export default Home;
